from __future__ import annotations

from vibe.config_values import (
    AUTO_THEME as AUTO_THEME,
    DEFAULT_LOG_LEVEL as DEFAULT_LOG_LEVEL,
    DEFAULT_THEME as DEFAULT_THEME,
    FALLBACK_THEME as FALLBACK_THEME,
)

DEFAULT_API_TIMEOUT = 720.0
DEFAULT_API_RETRY_MAX_ELAPSED_TIME = 300.0
DEFAULT_API_CONNECT_TIMEOUT = 10.0
DEFAULT_API_WRITE_TIMEOUT = 30.0
DEFAULT_API_POOL_TIMEOUT = 10.0
DEFAULT_AUTO_COMPACT_THRESHOLD = 90_000
